export {
  AI_SPECIALIZED_ASSISTANT_EXTENSION_ID,
  AI_SPECIALIZED_ASSISTANT_EXTENSION_PURPOSE,
  AI_SPECIALIZED_ASSISTANT_EXTENSION_RESPONSIBILITY,
  AI_SPECIALIZED_ASSISTANT_EXTENSION_NEVER_OWNS,
  AI_SPECIALIZED_ASSISTANT_IMPLEMENTED,
  AI_SPECIALIZED_ASSISTANT_EXTENSION_SLOT,
} from "./identity";

export type { AiSpecializedAssistantExtensionId } from "./identity";
