/**
 * COLLAB package-private internals.
 */

export const COLLAB_INTERNAL_PACKAGE = "collab/internal" as const;

export {
  COLLAB_PUBLIC_IMPORT_PREFIXES,
  COLLAB_INTERNAL_FOLDER_SEGMENTS,
  COLLAB_FORBIDDEN_CONSUMER_IMPORT_PREFIXES,
  COLLAB_FORBIDDEN_PEER_IMPORT_PREFIXES,
  COLLAB_ARCHITECTURAL_ALLOWED_DEPS,
  COLLAB_I8_ALLOWED_PEER_IMPORT_PREFIXES,
  COLLAB_ALLOWED_PUBLIC_INFRASTRUCTURE_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_SHARING_MEMBERSHIP_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_PERMISSIONS_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_ANNOTATION_DISCUSSION_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_REVIEW_MANAGEMENT_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_SUPPORTING_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_GOVERNANCE_AUDIT_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_CROSS_DOMAIN_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_HARDENING_REEXPORTS,
  COLLAB_ALLOWED_PUBLIC_CERTIFICATION_REEXPORTS,
  isAllowedCollabPublicImport,
  isForbiddenCollabConsumerImport,
  isForbiddenCollabPeerImport,
  isAllowedCollabI8PeerImport,
} from "./boundary-policy";
