/**
 * AI package-private internals.
 * AI-I0: package marker.
 * AI-I1: boundary policy + extension-point slots (no runtime intelligence).
 */

export const AI_INTERNAL_PACKAGE = "ai/internal" as const;

export {
  AI_PUBLIC_IMPORT_PREFIXES,
  AI_INTERNAL_FOLDER_SEGMENTS,
  AI_FORBIDDEN_CONSUMER_IMPORT_PREFIXES,
  AI_FORBIDDEN_PUBLIC_REEXPORT_PREFIXES,
  AI_ALLOWED_PUBLIC_INFRASTRUCTURE_REEXPORTS,
  AI_ALLOWED_PUBLIC_CORE_REEXPORTS,
  AI_ALLOWED_PUBLIC_SUPPORTING_REEXPORTS,
  AI_ALLOWED_PUBLIC_GOVERNANCE_REEXPORTS,
  AI_ALLOWED_PUBLIC_INTEGRATION_REEXPORTS,
  AI_ALLOWED_PUBLIC_EXTENSION_REEXPORTS,
  AI_FORBIDDEN_FOREIGN_INTERNAL_PREFIXES,
  AI_INFRASTRUCTURE_REQUIRED_DIRS,
  AI_INFRASTRUCTURE_REQUIRED_FILES,
  AI_CORE_REQUIRED_DIRS,
  AI_CORE_REQUIRED_FILES,
  AI_CONTEXTUAL_REQUIRED_DIRS,
  AI_I4_REQUIRED_DIRS,
  AI_SUPPORTING_REQUIRED_DIRS,
  AI_SUPPORTING_REQUIRED_FILES,
  AI_GOVERNANCE_REQUIRED_DIRS,
  AI_GOVERNANCE_REQUIRED_FILES,
  AI_INTEGRATION_REQUIRED_DIRS,
  AI_INTEGRATION_REQUIRED_FILES,
  AI_EXTENSION_REQUIRED_DIRS,
  AI_EXTENSION_REQUIRED_FILES,
  isAllowedAiPublicImport,
  isForbiddenAiConsumerImport,
  isForbiddenAiForeignInternalImport,
} from "./boundary-policy";

export {
  AI_EXTENSION_POINT_IDS,
  AI_EXTENSION_POINTS,
} from "./extension-points";

export type { AiExtensionPointId, AiExtensionPoint } from "./extension-points";
