/**
 * RELEASE-P1/P2 — Foundation barrel.
 */

export {
  RELEASE_DOMAIN_ID,
  RELEASE_DOMAIN_NAME,
  RELEASE_DOMAIN_ARCHITECTURAL_ROLE,
  RELEASE_DOMAIN_MOTTO,
  RELEASE_OWNERSHIP_PRINCIPLE,
  RELEASE_CENTRAL_RULE,
  RELEASE_P1_PHASE,
  RELEASE_P1_STATUS,
  RELEASE_P1_CERTIFICATION_STATUS,
  RELEASE_P2_PHASE,
  RELEASE_P2_STATUS,
  RELEASE_P2_CERTIFICATION_STATUS,
  RELEASE_FOUNDATION_IDENTITY,
} from "./identity";

export type {
  ReleaseFoundationIdentity,
  ReleaseP1Status,
  ReleaseP2Status,
} from "./identity";
