export {
  AI_CAPABILITY_GOVERNANCE_ID,
  AI_CAPABILITY_GOVERNANCE_PURPOSE,
  AI_CAPABILITY_GOVERNANCE_RESPONSIBILITY,
  AI_CAPABILITY_GOVERNANCE_NEVER_OWNS,
  AI_CAPABILITY_GOVERNANCE_LIFECYCLE,
} from "./identity";

export type { AiCapabilityGovernanceId } from "./identity";
