export {
  AI_PREDICTIVE_ASSISTANCE_EXTENSION_ID,
  AI_PREDICTIVE_ASSISTANCE_EXTENSION_PURPOSE,
  AI_PREDICTIVE_ASSISTANCE_EXTENSION_RESPONSIBILITY,
  AI_PREDICTIVE_ASSISTANCE_EXTENSION_NEVER_OWNS,
  AI_PREDICTION_IMPLEMENTED,
  AI_INFERENCE_ENABLED,
  AI_PREDICTIVE_ASSISTANCE_EXTENSION_SLOT,
} from "./identity";

export type { AiPredictiveAssistanceExtensionId } from "./identity";
