import type { LabUsageProfile } from "@/app/labUsageProfile";

import type { SmartStartIntentId } from "./types";

type IntentRule = {
  id: SmartStartIntentId;
  keywords: string[];
  recommendedProfile: LabUsageProfile;
  flowLabel: string;
  destinationLabel: string;
  priority: number;
};

export const INTENT_RULES: IntentRule[] = [
  {
    id: "expert-mode",
    keywords: [
      "avanzado",
      "experto",
      "laboratorio completo",
      "todas las herramientas",
      "acceso completo",
      "modo experto",
    ],
    recommendedProfile: "expert",
    flowLabel: "Modo experto",
    destinationLabel: "Datos → Avanzado (laboratorio completo)",
    priority: 60,
  },
  {
    id: "open-project",
    keywords: [
      "proyecto",
      "sgproj",
      "abrir proyecto",
      "archivo proyecto",
      "recuperar proyecto",
      "continuar proyecto",
    ],
    recommendedProfile: "standard",
    flowLabel: "Abrir proyecto",
    destinationLabel: "Panel de proyecto (.sgproj)",
    priority: 55,
  },
  {
    id: "compare-datasets",
    keywords: [
      "comparar",
      "comparacion",
      "compare",
      "a/b",
      "slot",
      "multi-dataset",
      "multivariante",
      "experimento",
      "grupos",
      "versus",
      " vs ",
      "control",
      "tratamiento",
    ],
    recommendedProfile: "standard",
    flowLabel: "Comparar datasets",
    destinationLabel: "Datos → Experimental → Multi-Dataset",
    priority: 50,
  },
  {
    id: "evaluate-publication",
    keywords: [
      "paper",
      "publicacion",
      "revista",
      "journal",
      "readiness",
      "sci-60",
      "sci-56",
      "metodologia",
      "evidence",
      "manuscrito",
      "artículo",
      "articulo",
      "publicar",
    ],
    recommendedProfile: "standard",
    flowLabel: "Evaluar publicación",
    destinationLabel: "Análisis → Estadística / Workflow de publicación",
    priority: 45,
  },
  {
    id: "math-graph",
    keywords: [
      "funcion",
      "función",
      "grafico matematico",
      "gráfico matemático",
      "curva",
      "ecuacion",
      "ecuación",
      "seno",
      "coseno",
      "tangente",
      "parabola",
      "parábola",
      "expresion",
      "expresión",
      "y=f",
      "matematica",
      "matemática",
      "plot",
      "sin(",
      "cos(",
    ],
    recommendedProfile: "standard",
    flowLabel: "Crear gráfico matemático",
    destinationLabel: "Datos → Curvas → Constructor",
    priority: 40,
  },
  {
    id: "analyze-dataset",
    keywords: [
      "csv",
      "excel",
      "xlsx",
      "xls",
      "ods",
      "txt",
      "datos",
      "dataset",
      "analisis",
      "análisis",
      "analizar",
      "importar",
      "tabla",
      "experimental",
      "observaciones",
      "series",
      "archivo de datos",
    ],
    recommendedProfile: "basic",
    flowLabel: "Analizar dataset",
    destinationLabel: "Datos → Experimental → Importación",
    priority: 30,
  },
];
