export {
  AI_DISCIPLINE_SPECIFIC_EXTENSION_ID,
  AI_DISCIPLINE_SPECIFIC_EXTENSION_PURPOSE,
  AI_DISCIPLINE_SPECIFIC_EXTENSION_RESPONSIBILITY,
  AI_DISCIPLINE_SPECIFIC_EXTENSION_NEVER_OWNS,
  AI_DISCIPLINE_LOGIC_IMPLEMENTED,
  AI_DISCIPLINE_SPECIFIC_EXTENSION_SLOT,
} from "./identity";

export type { AiDisciplineSpecificExtensionId } from "./identity";
