export {
  AI_CAPABILITY_CATALOG_ID,
  AI_CAPABILITY_CATALOG_PURPOSE,
  AI_CAPABILITY_CATALOG_RESPONSIBILITY,
  AI_CAPABILITY_CATALOG_NEVER_OWNS,
  AI_CAPABILITY_CATALOG_LIFECYCLE,
} from "./identity";

export type { AiCapabilityCatalogId } from "./identity";
